---
RecipeFormatVersion: '2020-01-25'
ComponentName: com.snap.robomaker.HelloWorld
ComponentVersion: 1.0.0
ComponentDescription: AWS RoboMaker application to rotate a Turtlebot3
ComponentPublisher: Amazon
Manifests:
  - Platform:
      os: linux
      architecture: arm64
    Lifecycle:
      Install: |
        snap install —devmode aws-hello-world_0.1_arm64.snap
      Run: |
        aws-hello-world.launch
    Artifacts:
      - Uri: s3://<S3_BUCKET>/aws-hello-world_0.1_arm64.snap